### ISSUE TITLE
Schema regression bug

### ISSUE THREAD

**Issue by thomersch** [thomersch/openstreetmap-calendar#159]
Reported through sentry:

```
AttributeError: 'NoneType' object has no attribute 'get'
(16 additional frame(s) were not displayed)
...
  File "osmcal/views.py", line 161, in get
    return render(
  File "osmcal/templatetags/schema.py", line 37, in schema_block
    evt.location_address.get("village"),
```

Probably introduced by #158 (cc @vkrause)

**Comment by vkrause** [comment]
Yep, that's from #158, sorry about that :( #160 should address this.

**Comment by thomersch** [comment]
Thanks for taking the time to fix this :)
